# Generated by Django 6.0.2 on 2026-07-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('title_np', models.CharField(blank=True, default='', max_length=200)),
                ('message_np', models.TextField(blank=True, default='')),
                ('priority', models.CharField(choices=[('critical', 'Critical - Overdue'), ('urgent', 'Urgent - Today'), ('high', 'High - 1-2 days'), ('medium', ' Medium - 3-4 days'), ('low', 'Low - 5+ days')], default='medium', max_length=10)),
                ('notification_type', models.CharField(choices=[('livestock', 'Livestock Alert'), ('crop', 'Crop Alert'), ('weather', 'Weather Alert'), ('admin', 'Admin Announcement')], default='livestock', max_length=20)),
                ('source_id', models.CharField(blank=True, max_length=100, null=True)),
                ('source_type', models.CharField(blank=True, max_length=50, null=True)),
                ('action_url', models.CharField(blank=True, max_length=500, null=True)),
                ('action_label', models.CharField(blank=True, max_length=100, null=True)),
                ('action_label_np', models.CharField(blank=True, max_length=100, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, help_text='Scheduled activity date for calendar views', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications_notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
