# Generated by Django 6.0.2 on 2026-05-18 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('critical', '💀 Critical - Overdue'), ('urgent', '🔴 Urgent - Today'), ('high', '🟠 High - 1-2 days'), ('medium', '🟡 Medium - 3-4 days'), ('low', '🟢 Low - 5+ days')], default='medium', max_length=10)),
                ('notification_type', models.CharField(choices=[('livestock', '🐄 Livestock Alert'), ('crop', '🌾 Crop Alert'), ('weather', '🌤️ Weather Alert'), ('admin', '📢 Admin Announcement')], default='livestock', max_length=20)),
                ('source_id', models.IntegerField(blank=True, help_text='ID of the related crop/animal', null=True)),
                ('source_type', models.CharField(blank=True, help_text='e.g., crop, livestock', max_length=50, null=True)),
                ('action_url', models.CharField(blank=True, max_length=500, null=True)),
                ('action_label', models.CharField(blank=True, max_length=100, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['farmer', 'is_read'], name='notificatio_farmer__99d34e_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx'), models.Index(fields=['notification_type', 'priority'], name='notificatio_notific_b9c0e7_idx')],
            },
        ),
    ]
