# Generated by Django 6.0.2 on 2026-05-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('livestock', 'Livestock Alert'), ('crop', 'Crop Alert'), ('weather', 'Weather Alert'), ('admin', 'Admin Announcement')], default='livestock', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('critical', 'Critical - Overdue'), ('urgent', 'Urgent - Today'), ('high', 'High - 1-2 days'), ('medium', ' Medium - 3-4 days'), ('low', 'Low - 5+ days')], default='medium', max_length=10),
        ),
    ]
