# Generated by Django 6.0.2 on 2026-05-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='source_id',
            field=models.CharField(blank=True, help_text='ID of the related crop/animal (UUID)', max_length=100, null=True),
        ),
    ]
