# Generated by Django 6.0.2 on 2026-05-21 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_source_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
