# Generated by Django 6.0.2 on 2026-03-14 09:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_np', models.CharField(blank=True, max_length=100)),
                ('avg_lifespan_years', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('gestation_days', models.IntegerField(blank=True, null=True)),
                ('is_milk_animal', models.BooleanField(default=False)),
                ('is_egg_animal', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('tag_number', models.CharField(max_length=50, unique=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('acquisition_date', models.DateField()),
                ('acquisition_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('dead', 'Dead'), ('butchered', 'Butchered')], default='active', max_length=20)),
                ('is_pregnant', models.BooleanField(default=False)),
                ('last_pregnancy_date', models.DateField(blank=True, null=True)),
                ('expected_birth_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to=settings.AUTH_USER_MODEL)),
                ('animal_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animals', to='livestock.animaltype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnimalExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('feed', 'Feed'), ('bedding', 'Bedding'), ('equipment', 'Equipment'), ('breeding', 'Breeding Service'), ('transport', 'Transport'), ('other', 'Other')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('vendor_name', models.CharField(blank=True, max_length=255)),
                ('vendor_contact', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='livestock.animal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AnimalIncome',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('milk_sale', 'Milk Sale'), ('egg_sale', 'Egg Sale'), ('animal_sale', 'Animal Sale'), ('offspring_sale', 'Offspring Sale'), ('wool_sale', 'Wool Sale'), ('manure_sale', 'Manure Sale'), ('subsidy', 'Government Subsidy'), ('other', 'Other Income')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('buyer_name', models.CharField(blank=True, max_length=255)),
                ('buyer_contact', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='livestock.animal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_incomes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('health_type', models.CharField(choices=[('checkup', 'Regular Checkup'), ('sick', 'Sickness'), ('injury', 'Injury'), ('treatment', 'Treatment'), ('other', 'Other')], default='checkup', max_length=20)),
                ('diagnosis', models.CharField(max_length=255)),
                ('treatment', models.TextField(blank=True)),
                ('treatment_date', models.DateField()),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('vet_name', models.CharField(blank=True, max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='livestock.animal')),
            ],
            options={
                'ordering': ['-treatment_date'],
            },
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vaccine_name', models.CharField(max_length=255)),
                ('vaccine_date', models.DateField()),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('administered_by', models.CharField(blank=True, max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='livestock.animal')),
            ],
            options={
                'ordering': ['-vaccine_date'],
            },
        ),
        migrations.CreateModel(
            name='BreedingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('breeding_date', models.DateField()),
                ('successful', models.BooleanField(default=False)),
                ('expected_birth_date', models.DateField(blank=True, null=True)),
                ('actual_birth_date', models.DateField(blank=True, null=True)),
                ('offspring_count', models.IntegerField(default=0)),
                ('sire_name', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeding_records', to='livestock.animal')),
                ('sire_animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sired_offspring', to='livestock.animal')),
            ],
            options={
                'ordering': ['-breeding_date'],
                'unique_together': {('animal', 'breeding_date')},
            },
        ),
        migrations.CreateModel(
            name='MilkRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('quantity_liters', models.DecimalField(decimal_places=2, max_digits=8)),
                ('milk_time', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening'), ('total', 'Total Day')], default='total', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_records', to='livestock.animal')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('animal', 'date', 'milk_time')},
            },
        ),
    ]
