# Generated by Django 6.0.2 on 2026-03-02 15:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_np', models.CharField(blank=True, max_length=100)),
                ('avg_lifespan_years', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('gestation_days', models.IntegerField(blank=True, null=True)),
                ('is_milk_animal', models.BooleanField(default=False)),
                ('is_egg_animal', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('tag_number', models.CharField(max_length=50, unique=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('acquistion_date', models.DateField()),
                ('acquistion_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('dead', 'Dead'), ('butchered', 'Butchered')], default='active', max_length=20)),
                ('is_pregnent', models.BooleanField(default=False)),
                ('last_pregnancy_date', models.DateField(blank=True, null=True)),
                ('expected_birth_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to=settings.AUTH_USER_MODEL)),
                ('animal_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animals', to='livestock.animaltype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
