# Generated by Django 6.0.2 on 2026-03-28 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livestock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='animalexpense',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='livestock.animal'),
        ),
        migrations.AddField(
            model_name='animalexpense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='animalincome',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='livestock.animal'),
        ),
        migrations.AddField(
            model_name='animalincome',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_incomes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='animal',
            name='animal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animals', to='livestock.animaltype'),
        ),
        migrations.AddField(
            model_name='breedingrecord',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeding_records', to='livestock.animal'),
        ),
        migrations.AddField(
            model_name='breedingrecord',
            name='sire_animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sired_offspring', to='livestock.animal'),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='livestock.animal'),
        ),
        migrations.AddField(
            model_name='milkrecord',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_records', to='livestock.animal'),
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='livestock.animal'),
        ),
        migrations.AlterUniqueTogether(
            name='breedingrecord',
            unique_together={('animal', 'breeding_date')},
        ),
        migrations.AlterUniqueTogether(
            name='milkrecord',
            unique_together={('animal', 'date', 'milk_time')},
        ),
    ]
