# Generated by Django 6.0.2 on 2026-03-02 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='is_pregnent',
            new_name='is_pregnant',
        ),
    ]
