# Generated by Django 6.0.2 on 2026-04-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='acquisition_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
