# Generated by Django 6.0.2 on 2026-03-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='tag_number',
            field=models.CharField(max_length=50),
        ),
    ]
