# Generated by Django 6.0.2 on 2026-03-02 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0002_rename_is_pregnent_animal_is_pregnant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='acquistion_cost',
            new_name='acquisition_cost',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='acquistion_date',
            new_name='acquisition_date',
        ),
    ]
