# Generated by Django 6.0.2 on 2026-04-14 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0002_alter_animal_acquisition_date'),
        ('livestock', '0002_initial'),
    ]

    operations = [
    ]
