# Generated by Django 6.0.2 on 2026-03-07 16:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0003_rename_acquistion_cost_animal_acquisition_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('health_type', models.CharField(choices=[('checkup', 'Regular Checkup'), ('sick', 'Sickness'), ('injury', 'Injury'), ('treatment', 'Treatment'), ('other', 'Other')], default='checkup', max_length=20)),
                ('diagnosis', models.CharField(max_length=255)),
                ('treatment', models.TextField(blank=True)),
                ('treatment_date', models.DateField()),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('vet_name', models.CharField(blank=True, max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='livestock.animal')),
            ],
            options={
                'ordering': ['-treatment_date'],
            },
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vaccine_name', models.CharField(max_length=255)),
                ('vaccine_date', models.DateField()),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('administered_by', models.CharField(blank=True, max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='livestock.animal')),
            ],
            options={
                'ordering': ['-vaccine_date'],
            },
        ),
    ]
