# Generated by Django 6.0.2 on 2026-04-21 03:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0003_merge_0002_alter_animal_acquisition_date_0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='animal',
            unique_together={('farmer', 'tag_number')},
        ),
    ]
