# Generated by Django 6.0.2 on 2026-03-08 12:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0004_healthrecord_vaccinationrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreedingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('breeding_date', models.DateField()),
                ('successful', models.BooleanField(default=False)),
                ('expected_birth_date', models.DateField(blank=True, null=True)),
                ('actual_birth_date', models.DateField(blank=True, null=True)),
                ('offspring_count', models.IntegerField(default=0)),
                ('sire_name', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeding_records', to='livestock.animal')),
                ('sire_animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sired_offspring', to='livestock.animal')),
            ],
            options={
                'ordering': ['-breeding_date'],
            },
        ),
        migrations.CreateModel(
            name='MilkRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('quantity_liters', models.DecimalField(decimal_places=2, max_digits=8)),
                ('milk_time', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening'), ('total', 'Total Day')], default='total', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_records', to='livestock.animal')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('animal', 'date', 'milk_time')},
            },
        ),
    ]
