# Generated by Django 6.0.2 on 2026-03-08 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0005_breedingrecord_milkrecord'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='breedingrecord',
            unique_together={('animal', 'breeding_date')},
        ),
    ]
