# Generated by Django 6.0.2 on 2026-07-04 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_notification_target_crop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message_np',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_np',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
