# Generated by Django 6.0.2 on 2026-07-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_notification_message_np_notification_title_np'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('broadcast', 'Broadcast (All Farmers)'), ('targeted', 'Targeted (Specific Farmers)'), ('weather_alert', 'Weather Alert'), ('crop_reminder', 'Crop Care Reminder'), ('animal_reminder', 'Animal Care Reminder'), ('marketing', 'Marketing/Promotion')], max_length=50),
        ),
    ]
