# Generated by Django 6.0.2 on 2026-02-26 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_np', models.CharField(blank=True, max_length=255)),
                ('variety', models.CharField(blank=True, max_length=255)),
                ('field_name', models.CharField(max_length=255)),
                ('field_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area_unit', models.CharField(choices=[('ropani', 'Ropani'), ('kattha', 'Kattha'), ('bigha', 'Bigha'), ('hectare', 'Hectare')], default='ropani', max_length=50)),
                ('planting_date', models.DateField()),
                ('expected_harvest_date', models.DateField(blank=True, null=True)),
                ('growth_stage', models.CharField(choices=[('seeding', 'Seeding'), ('vegetative', 'Vegetative'), ('flowering', 'Flowering'), ('fruiting', 'Fruiting'), ('harvest', 'Harvest')], default='seeding', max_length=50)),
                ('irrigation_type', models.CharField(choices=[('rainfed', 'Rainfed'), ('irrigated', 'Irrigated'), ('drip', 'Drip'), ('sprinkler', 'Sprinkler')], default='rainfed', max_length=50)),
                ('soil_type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('harvested', 'Harvested'), ('done', 'Done')], default='active', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
