# Generated by Django 6.0.2 on 2026-07-03 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cropexpense',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='crops.crop'),
        ),
        migrations.AddField(
            model_name='cropexpense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cropincome',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='crops.crop'),
        ),
        migrations.AddField(
            model_name='cropincome',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_incomes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='croprecommendationhistory',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='croptypeconfig',
            index=models.Index(fields=['crop_name', 'region', 'variety', 'season'], name='crops_cropt_crop_na_98a420_idx'),
        ),
        migrations.AddIndex(
            model_name='croptypeconfig',
            index=models.Index(fields=['crop_name', 'is_active'], name='crops_cropt_crop_na_36e608_idx'),
        ),
        migrations.AddConstraint(
            model_name='croptypeconfig',
            constraint=models.UniqueConstraint(fields=('crop_name', 'variety', 'region', 'season'), name='unique_crop_config'),
        ),
        migrations.AddField(
            model_name='cropactivityrule',
            name='crop_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crops.croptypeconfig'),
        ),
        migrations.AddField(
            model_name='fertilizerrecord',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fertilizers', to='crops.crop'),
        ),
        migrations.AddField(
            model_name='fertilizerrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fertilizer_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='harvestrecord',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='crops.crop'),
        ),
        migrations.AddField(
            model_name='harvestrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labour',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labour_records', to='crops.crop'),
        ),
        migrations.AddField(
            model_name='labour',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labour_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pesticiderecord',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesticides', to='crops.crop'),
        ),
        migrations.AddField(
            model_name='pesticiderecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesticide_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cropactivityrule',
            index=models.Index(fields=['crop_config', 'growth_stage', 'is_active'], name='crops_cropa_crop_co_f646f8_idx'),
        ),
        migrations.AddIndex(
            model_name='cropactivityrule',
            index=models.Index(fields=['growth_stage', 'is_active'], name='crops_cropa_growth__a48cac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cropactivityrule',
            unique_together={('crop_config', 'growth_stage', 'title')},
        ),
    ]
