# Generated by Django 6.0.2 on 2026-03-28 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cropexpense',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='crops.crop'),
        ),
        migrations.AddField(
            model_name='cropexpense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cropincome',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='crops.crop'),
        ),
        migrations.AddField(
            model_name='cropincome',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_incomes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fertilizerrecord',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fertilizers', to='crops.crop'),
        ),
        migrations.AddField(
            model_name='fertilizerrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fertilizer_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='harvestrecord',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='crops.crop'),
        ),
        migrations.AddField(
            model_name='harvestrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pesticiderecord',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesticides', to='crops.crop'),
        ),
        migrations.AddField(
            model_name='pesticiderecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesticide_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
