# Generated by Django 6.0.2 on 2026-04-09 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CropKnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, unique=True)),
                ('name_np', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('cereal', 'Cereal'), ('pulse', 'Pulse'), ('cash_crop', 'Cash Crop'), ('vegetable', 'Vegetable')], max_length=20)),
                ('best_season', models.CharField(choices=[('spring', 'Spring'), ('monsoon', 'Monsoon'), ('autumn', 'Autumn'), ('winter', 'Winter')], max_length=20)),
                ('other_seasons', models.CharField(blank=True, help_text='Comma separated: spring,autumn', max_length=200)),
                ('temp_min', models.FloatField(help_text='Minimum temperature (°C)')),
                ('temp_max', models.FloatField(help_text='Maximum temperature (°C)')),
                ('temp_ideal', models.FloatField(help_text='Ideal temperature (°C)')),
                ('soil_ideal', models.CharField(max_length=50)),
                ('soil_other', models.CharField(blank=True, help_text='Comma separated: clay,silty', max_length=200)),
                ('ph_min', models.FloatField()),
                ('ph_max', models.FloatField()),
                ('ph_ideal', models.FloatField()),
                ('water_req', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('region_suitable', models.CharField(help_text='Comma separated: terai,mid-hill,hill,mountain', max_length=200)),
                ('drought_tolerance', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('frost_sensitive', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('labor_req', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('storage_life', models.CharField(choices=[('very_short', 'Very Short (<1 week)'), ('short', 'Short (1-4 weeks)'), ('medium', 'Medium (1-3 months)'), ('long', 'Long (>3 months)')], max_length=20)),
                ('n_need', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('p_need', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('k_need', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='CropRecommendationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_type', models.CharField(max_length=50)),
                ('ph', models.FloatField()),
                ('season', models.CharField(max_length=50)),
                ('water_availability', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=50)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('recommendations', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
