# Generated by Django 6.0.2 on 2026-04-02 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_alter_crop_id'),
        ('crops', '0002_initial'),
    ]

    operations = [
    ]
