# Generated by Django 6.0.2 on 2026-04-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0003_cropknowledgebase_croprecommendationhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropknowledgebase',
            name='frost_sensitive',
            field=models.CharField(choices=[('yes', 'Yes (Frost kills it)'), ('no', 'No (Tolerant)'), ('tolerant', 'Tolerant (May survive light frost)')], default='no', max_length=10),
        ),
    ]
