# Generated by Django 6.0.2 on 2026-04-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0004_alter_cropknowledgebase_frost_sensitive'),
    ]

    operations = [
        migrations.AddField(
            model_name='croprecommendationhistory',
            name='experience',
            field=models.CharField(default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='croprecommendationhistory',
            name='frost_risk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='croprecommendationhistory',
            name='goal',
            field=models.CharField(default='mixed', max_length=20),
        ),
    ]
