# Generated by Django 6.0.2 on 2026-04-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0005_croprecommendationhistory_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='croprecommendationhistory',
            name='frost_risk',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
