# Generated by Django 6.0.2 on 2026-04-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0006_alter_croprecommendationhistory_frost_risk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropknowledgebase',
            name='k_need',
            field=models.FloatField(default=40, help_text='Potassium requirement (kg/hectare) - Low:10-30, Medium:30-60, High:60-90'),
        ),
        migrations.AlterField(
            model_name='cropknowledgebase',
            name='n_need',
            field=models.FloatField(default=60, help_text='Nitrogen requirement (kg/hectare) - Low:20-40, Medium:40-80, High:80-120'),
        ),
        migrations.AlterField(
            model_name='cropknowledgebase',
            name='p_need',
            field=models.FloatField(default=40, help_text='Phosphorus requirement (kg/hectare) - Low:10-30, Medium:30-60, High:60-90'),
        ),
    ]
