# Generated by Django 6.0.2 on 2026-04-21 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0007_alter_cropknowledgebase_k_need_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropincome',
            name='source',
            field=models.CharField(choices=[('crop_sale', 'Crop Sale'), ('subsidy', 'Government Subsidy'), ('insurance', 'Crop Insurance'), ('seed_sale', 'Seed Sale '), ('other', 'Other Income')], max_length=50),
        ),
    ]
