# Generated by Django 6.0.2 on 2026-04-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0008_alter_cropincome_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropexpense',
            name='category',
            field=models.CharField(choices=[('seed', 'Seeds'), ('labor', 'Labor '), ('land_rent', 'Land Rent'), ('irrigation', 'Irrigation'), ('equipment', 'Equipment'), ('transport', 'Transportation'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cropincome',
            name='source',
            field=models.CharField(choices=[('crop_sale', 'Crop Sale'), ('subsidy', 'Government Subsidy'), ('insurance', 'Crop Insurance'), ('seed_sale', 'Seed Sale'), ('other', 'Other Income')], max_length=50),
        ),
    ]
