# Generated by Django 6.0.2 on 2026-05-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0009_alter_cropexpense_category_alter_cropincome_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='croprecommendationhistory',
            name='ph',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
