# Generated by Django 6.0.2 on 2026-05-19 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0009_alter_cropexpense_category_alter_cropincome_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropTypeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('region', models.CharField(choices=[('terai', 'Terai'), ('hilly', 'Hilly'), ('himalayan', 'Himalayan')], max_length=50)),
                ('variety', models.CharField(blank=True, help_text='Optional variety name', max_length=100)),
                ('germination_start_day', models.IntegerField(default=0)),
                ('germination_end_day', models.IntegerField(default=10)),
                ('vegetative_start_day', models.IntegerField(default=11)),
                ('vegetative_end_day', models.IntegerField(default=40)),
                ('flowering_start_day', models.IntegerField(default=41)),
                ('flowering_end_day', models.IntegerField(default=60)),
                ('maturation_start_day', models.IntegerField(default=61)),
                ('maturation_end_day', models.IntegerField(default=85)),
                ('harvest_start_day', models.IntegerField(default=86)),
                ('harvest_end_day', models.IntegerField(default=120)),
                ('total_growing_days', models.IntegerField(default=120)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('crop_name', 'region', 'variety'), name='unique_crop_region_variety')],
            },
        ),
        migrations.CreateModel(
            name='CropActivityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('growth_stage', models.CharField(choices=[('germination', 'Germination'), ('vegetative', 'Vegetative'), ('flowering', 'Flowering'), ('maturation', 'Maturation'), ('harvest', 'Harvest')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('title_np', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('description_np', models.TextField(blank=True)),
                ('measurements', models.TextField(blank=True, help_text='e.g., Urea: 4.8 Kg/Ropani')),
                ('target_pest', models.TextField(blank=True, help_text='e.g., Blast, Bacterial leaf blight')),
                ('recommendations', models.TextField(blank=True, help_text='Additional tips for farmers')),
                ('day_offset', models.IntegerField(default=0, help_text='0 = any day in this stage, or specific day number (e.g., 10 = exactly on day 10 of the stage)')),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10)),
                ('order', models.IntegerField(default=0, help_text='Lower number = shown first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crops.croptypeconfig')),
            ],
            options={
                'ordering': ['crop_config', 'growth_stage', 'order', 'day_offset'],
                'unique_together': {('crop_config', 'growth_stage', 'title')},
            },
        ),
    ]
