# Generated by Django 6.0.2 on 2026-05-19 18:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0010_croptypeconfig_cropactivityrule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='croptypeconfig',
            options={'ordering': ['crop_name', 'region', 'variety', 'season']},
        ),
        migrations.RemoveConstraint(
            model_name='croptypeconfig',
            name='unique_crop_region_variety',
        ),
        migrations.AddField(
            model_name='croptypeconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='croptypeconfig',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='croptypeconfig',
            name='season',
            field=models.CharField(blank=True, choices=[('spring', 'Spring (Feb-Apr)'), ('summer', 'Summer (May-Jul)'), ('monsoon', 'Monsoon (Jun-Sep)'), ('autumn', 'Autumn (Sep-Nov)'), ('winter', 'Winter (Dec-Feb)')], help_text='Growing season', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='croptypeconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='cropactivityrule',
            index=models.Index(fields=['crop_config', 'growth_stage', 'is_active'], name='crops_cropa_crop_co_f646f8_idx'),
        ),
        migrations.AddIndex(
            model_name='cropactivityrule',
            index=models.Index(fields=['growth_stage', 'is_active'], name='crops_cropa_growth__a48cac_idx'),
        ),
        migrations.AddIndex(
            model_name='croptypeconfig',
            index=models.Index(fields=['crop_name', 'region', 'variety', 'season'], name='crops_cropt_crop_na_98a420_idx'),
        ),
        migrations.AddIndex(
            model_name='croptypeconfig',
            index=models.Index(fields=['crop_name', 'is_active'], name='crops_cropt_crop_na_36e608_idx'),
        ),
        migrations.AddConstraint(
            model_name='croptypeconfig',
            constraint=models.UniqueConstraint(fields=('crop_name', 'variety', 'region', 'season'), name='unique_crop_config'),
        ),
    ]
