# Generated by Django 6.0.2 on 2026-05-21 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0011_alter_croptypeconfig_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropactivityrule',
            name='severity',
        ),
    ]
