# Generated by Django 6.0.2 on 2026-05-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0012_remove_cropactivityrule_severity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='croprecommendationhistory',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='croprecommendationhistory',
            name='frost_risk',
        ),
        migrations.RemoveField(
            model_name='croprecommendationhistory',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='croprecommendationhistory',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='croprecommendationhistory',
            name='water_availability',
        ),
        migrations.AddField(
            model_name='cropknowledgebase',
            name='altitude_max',
            field=models.IntegerField(default=3000),
        ),
        migrations.AddField(
            model_name='cropknowledgebase',
            name='altitude_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cropknowledgebase',
            name='day_length_sensitive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cropknowledgebase',
            name='day_length_type',
            field=models.CharField(blank=True, choices=[('short-day', 'Short Day'), ('long-day', 'Long Day'), ('day-neutral', 'Day Neutral')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cropknowledgebase',
            name='growing_days',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='cropknowledgebase',
            name='water_logging_tolerance',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='croprecommendationhistory',
            name='elevation_risk',
            field=models.BooleanField(default=False, help_text='Frost risk area'),
        ),
        migrations.AddField(
            model_name='croprecommendationhistory',
            name='farming_goal',
            field=models.CharField(choices=[('profit', 'Profit'), ('food_security', 'Food Security'), ('mixed', 'Mixed'), ('subsistence', 'Subsistence')], default='mixed', max_length=20),
        ),
        migrations.AddField(
            model_name='croprecommendationhistory',
            name='k',
            field=models.FloatField(blank=True, help_text='Potassium kg/ha', null=True),
        ),
        migrations.AddField(
            model_name='croprecommendationhistory',
            name='labor_availability',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='croprecommendationhistory',
            name='market_distance',
            field=models.CharField(choices=[('near', 'Near'), ('medium', 'Medium'), ('far', 'Far')], default='near', max_length=20),
        ),
        migrations.AddField(
            model_name='croprecommendationhistory',
            name='n',
            field=models.FloatField(blank=True, help_text='Nitrogen kg/ha', null=True),
        ),
        migrations.AddField(
            model_name='croprecommendationhistory',
            name='p',
            field=models.FloatField(blank=True, help_text='Phosphorus kg/ha', null=True),
        ),
        migrations.AddField(
            model_name='croprecommendationhistory',
            name='temperature_override',
            field=models.FloatField(blank=True, help_text='Temperature in °C', null=True),
        ),
        migrations.AddField(
            model_name='croprecommendationhistory',
            name='water_source',
            field=models.CharField(choices=[('rainfed_only', 'Rainfed Only'), ('canal', 'Canal'), ('well', 'Well'), ('river', 'River'), ('drip_irrigation', 'Drip Irrigation')], default='rainfed_only', max_length=50),
        ),
        migrations.AlterField(
            model_name='cropknowledgebase',
            name='best_season',
            field=models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('monsoon', 'Monsoon'), ('autumn', 'Autumn'), ('winter', 'Winter')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cropknowledgebase',
            name='category',
            field=models.CharField(choices=[('cereal', 'Cereal'), ('pulse', 'Pulse'), ('cash_crop', 'Cash Crop'), ('vegetable', 'Vegetable'), ('tuber', 'Tuber'), ('oilseed', 'Oilseed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='croprecommendationhistory',
            name='ph',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='croprecommendationhistory',
            name='region',
            field=models.CharField(choices=[('terai', 'Terai'), ('mid-hill', 'Mid-Hill'), ('hill', 'Hill'), ('mountain', 'Mountain')], max_length=50),
        ),
        migrations.AlterField(
            model_name='croprecommendationhistory',
            name='season',
            field=models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('monsoon', 'Monsoon'), ('autumn', 'Autumn'), ('winter', 'Winter')], max_length=20),
        ),
        migrations.AlterField(
            model_name='croprecommendationhistory',
            name='soil_type',
            field=models.CharField(choices=[('clay', 'Clay'), ('loamy', 'Loamy'), ('sandy', 'Sandy'), ('silty', 'Silty'), ('clay_loam', 'Clay Loam')], max_length=50),
        ),
    ]
