# Generated by Django 6.0.2 on 2026-05-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0013_remove_croprecommendationhistory_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='croprecommendationhistory',
            name='drought_risk',
            field=models.CharField(choices=[('high', 'High Risk'), ('medium', 'Medium Risk'), ('low', 'Low Risk')], default='medium', help_text='Drought risk level at farm location', max_length=10),
        ),
    ]
