# Generated by Django 6.0.2 on 2026-05-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0014_croprecommendationhistory_drought_risk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='croprecommendationhistory',
            old_name='temperature_override',
            new_name='temperature',
        ),
        migrations.RemoveField(
            model_name='croprecommendationhistory',
            name='elevation_risk',
        ),
        migrations.AddField(
            model_name='croprecommendationhistory',
            name='frost_risk',
            field=models.BooleanField(default=False, help_text='Does your area experience frost?'),
        ),
    ]
