# Generated by Django 6.0.2 on 2026-07-02 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0015_rename_temperature_override_croprecommendationhistory_temperature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='growth_stage_manual_override',
            field=models.BooleanField(default=False, help_text='If True, growth_stage was manually set by the user and will no longer be auto-calculated'),
        ),
    ]
