# Generated by Django 6.0.2 on 2026-04-07 06:34

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.utils.timezone
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(error_messages={'invalid': 'Enter a valid email address', 'unique': 'A user with this email already exists'}, max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, error_messages={'unique': 'This phone number is already registered'}, max_length=10, null=True, unique=True, validators=[users.models.validate_nepal_phone])),
                ('date_of_birth', models.DateField(blank=True, null=True, validators=[users.models.validate_min_age])),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('geographical_region', models.CharField(blank=True, choices=[('terai', 'Terai Region'), ('hilly', 'Hilly Region'), ('mountain', 'Mountain Region'), ('kathmandu_valley', 'Kathmandu Valley')], max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.MaxLengthValidator(200)])),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('is_farmer', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('farm_name', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(3, message='Farm name must be at least 3 characters'), django.core.validators.MaxLengthValidator(100, message='Farm name cannot exceed 100 characters'), django.core.validators.RegexValidator(code='invalid_farm_name', message='Farm name can only contain letters, numbers, spaces, hyphens, and underscores', regex='^[a-zA-Z0-9\\s\\-_]+$')])),
                ('total_farm_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[users.models.validate_farm_area])),
                ('farm_village', models.CharField(blank=True, max_length=100, null=True)),
                ('farm_municipality', models.CharField(blank=True, max_length=100, null=True)),
                ('farm_district', models.CharField(blank=True, max_length=100, null=True)),
                ('farm_province', models.CharField(blank=True, max_length=50, null=True)),
                ('farm_ward_number', models.IntegerField(blank=True, null=True, validators=[users.models.validate_ward_number])),
                ('farm_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, validators=[django.core.validators.MaxValueValidator(90), django.core.validators.MinValueValidator(-90)])),
                ('farm_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, validators=[django.core.validators.MaxValueValidator(180), django.core.validators.MinValueValidator(-180)])),
                ('farm_altitude', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[users.models.validate_altitude])),
                ('farm_soil_type', models.CharField(blank=True, choices=[('alluvial', 'Alluvial Soil'), ('clay', 'Clay Soil'), ('sandy', 'Sandy Soil'), ('loamy', 'Loamy Soil'), ('peaty', 'Peaty Soil'), ('chalky', 'Chalky Soil'), ('silt', 'Silt Soil'), ('laterite', 'Laterite Soil'), ('mountain', 'Mountain Soil'), ('terra_rossa', 'Terra Rossa')], max_length=50, null=True)),
                ('water_source', models.CharField(blank=True, choices=[('irrigation', 'Irrigation System'), ('river', 'River'), ('well', 'Well'), ('borewell', 'Borewell'), ('tube_well', 'Tube Well'), ('pond', 'Pond'), ('rainwater', 'Rainwater Harvesting'), ('spring', 'Natural Spring'), ('canal', 'Canal')], max_length=50, null=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('email_verification_token', models.CharField(blank=True, max_length=255, null=True)),
                ('reset_password_token', models.CharField(blank=True, max_length=255, null=True)),
                ('reset_password_expires', models.DateTimeField(blank=True, null=True)),
                ('agreed_to_terms', models.BooleanField(default=False)),
                ('agreed_to_privacy', models.BooleanField(default=False)),
                ('terms_version', models.CharField(default='1.0', max_length=10)),
                ('privacy_version', models.CharField(default='1.0', max_length=10)),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('privacy_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-date_joined'],
                'indexes': [models.Index(fields=['email'], name='users_user_email_6f2530_idx'), models.Index(fields=['phone'], name='users_user_phone_9474e8_idx'), models.Index(fields=['is_farmer'], name='users_user_is_farm_f96a09_idx'), models.Index(fields=['district'], name='users_user_distric_a19c90_idx'), models.Index(fields=['farm_district'], name='users_user_farm_di_4bc386_idx')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
