# Generated by Django 6.0.2 on 2026-04-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='geographical_region',
            field=models.CharField(blank=True, choices=[('terai', 'Terai Region'), ('hilly', 'Hilly Region'), ('himalayan', 'himalayan')], max_length=50, null=True),
        ),
    ]
