# Generated by Django 6.0.2 on 2026-04-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_geographical_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_farmer',
            field=models.BooleanField(default=True),
        ),
    ]
