# Generated by Django 6.0.2 on 2026-05-21 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_is_farmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_reminder_generation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
